exports.home = (req, res) => res.render("home")
exports.decode = (req,res) => res.render("decode")
exports.about = (req, res) => res.render("about")
exports.steg = (req,res) => res.render("stegTests")
exports.serverError = (req,res) => res.render("500")
exports.notFound = (req,res) => res.render("404")
